#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Matthias Brukner
"""Generate self-contained Verilog/C font exports and a vector specimen."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CODES = list(range(0x20, 0x7f)) + [0xb0]


def load_font(path=ROOT / 'font.json'):
    data = json.loads(path.read_text(encoding='utf-8'))
    if (data['width'], data['height'], data['advance']) != (5, 7, 6):
        raise ValueError('Expected 5x7 glyphs with six-pixel advance')
    glyphs = data['glyphs']
    if set(glyphs) != {chr(code) for code in CODES}:
        raise ValueError('Expected exactly printable ASCII plus U+00B0')
    for char, pattern in glyphs.items():
        rows = pattern.split('/')
        if len(rows) != 7 or any(len(row) != 5 or set(row) - {'0', '1'} for row in rows):
            raise ValueError(f'Invalid glyph {char!r}')
    return data


def outputs(data):
    glyphs = data['glyphs']
    notice = '// SPDX-License-Identifier: MIT\n// Copyright (c) 2026 Matthias Brukner\n'
    notice += '// Generated by generate.py from font.json; do not edit.\n'
    verilog = [notice, '''// Pure Verilog-2001. Asynchronous lookup, no clock/reset or vendor primitive.
// glyph_o[34] is top-left; bit (34 - y*5 - x) is pixel (x,y).
module wb_font5x7 (
    input wire [7:0] char_i,
    output wire [34:0] glyph_o
);
    wire [6:0] index = char_i >= 8'h20 && char_i <= 8'h7e ? char_i - 8'h20 :
                       char_i == 8'hb0 ? 7'd95 : 7'd31; // '?' fallback
    (* rom_style = "distributed" *) reg [34:0] glyphs [0:95];
    initial begin
''']
    for index, code in enumerate(CODES):
        bits = glyphs[chr(code)].replace('/', '_')
        verilog.append(f"        glyphs[{index}] = 35'b{bits}; // 0x{code:02X}\n")
    verilog += ['    end\n    assign glyph_o = glyphs[index];\nendmodule\n']

    header = [notice, '''#ifndef WB_FONT5X7_H
#define WB_FONT5X7_H
#include <stdint.h>

#define WB_FONT5X7_WIDTH 5u
#define WB_FONT5X7_HEIGHT 7u
#define WB_FONT5X7_ADVANCE 6u
#define WB_FONT5X7_LINE_HEIGHT 8u
#define WB_FONT5X7_DEGREE 0xB0u

/* Seven row bytes per glyph: bit 4 leftmost, bit 0 rightmost; high bits zero.
 * Pass unsigned codepoints, not signed chars or UTF-8 bytes for non-ASCII.
 * 0x20..0x7E = ASCII, 0xB0 = degree. All other values render '?'. */
static const uint8_t wb_font5x7_rows[96][7] = {
''']
    for code in CODES:
        rows = ', '.join(f'0x{int(row, 2):02x}' for row in glyphs[chr(code)].split('/'))
        header.append(f'    {{{rows}}}, /* 0x{code:02X} */\n')
    header += ['''};

static inline unsigned wb_font5x7_index(uint32_t codepoint) {
    if (codepoint >= 0x20u && codepoint <= 0x7eu) return (unsigned)(codepoint - 0x20u);
    return codepoint == WB_FONT5X7_DEGREE ? 95u : 31u;
}
static inline uint8_t wb_font5x7_row(uint32_t codepoint, unsigned y) {
    return y < WB_FONT5X7_HEIGHT ? wb_font5x7_rows[wb_font5x7_index(codepoint)][y] : 0u;
}
static inline unsigned wb_font5x7_pixel(uint32_t codepoint, unsigned x, unsigned y) {
    return x < WB_FONT5X7_WIDTH && y < WB_FONT5X7_HEIGHT
        ? (unsigned)((wb_font5x7_row(codepoint, y) >> (4u - x)) & 1u) : 0u;
}
#endif
''']

    # SVG remains code-native and self-contained. Glyph pixels are rectangles,
    # not text rendered through a locally installed font.
    svg = ['<svg xmlns="http://www.w3.org/2000/svg" width="800" height="640" viewBox="0 0 800 640">',
           '<rect width="800" height="640" fill="#fff"/>',
           '<text x="24" y="30" font-family="sans-serif" font-size="20">Wildbits 5x7 — ASCII + degree</text>']
    def draw(text, x, y, scale):
        for char in text:
            for row, pattern in enumerate(glyphs.get(char, glyphs['?']).split('/')):
                for col, value in enumerate(pattern):
                    if value == '1':
                        svg.append(f'<rect x="{x+col*scale}" y="{y+row*scale}" width="{scale}" height="{scale}" fill="#111"/>')
            x += 6*scale
    draw('FPGA  65°C', 24, 52, 3)
    draw('The quick brown fox jumps over', 24, 92, 3)
    draw('the lazy dog. 0123456789', 24, 122, 3)
    for index, code in enumerate(CODES):
        x, y = 24 + (index % 16)*48, 180 + (index // 16)*72
        svg.append(f'<text x="{x}" y="{y}" font-family="monospace" font-size="10">{code:02X}</text>')
        draw(chr(code), x+6, y+8, 3)
    svg.append('</svg>\n')
    return {'wb_font5x7.v': ''.join(verilog), 'wb_font5x7.h': ''.join(header),
            'specimen.svg': '\n'.join(svg)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Check committed exports without writing')
    parser.add_argument('--output-dir', type=Path, default=ROOT / 'generated')
    args = parser.parse_args()
    for name, content in outputs(load_font()).items():
        target = args.output_dir / name
        if args.check:
            if not target.is_file() or target.read_text(encoding='utf-8') != content:
                raise SystemExit(f'Stale/missing export: {target}')
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding='utf-8')
    print('PASS: 96 glyphs; deterministic Verilog, C/C++ and SVG exports')


if __name__ == '__main__':
    main()
