# Derive the K2 menu from the canonical config, without changing MEGA65 builds.
# Called at project creation and before every synthesis (including GUI runs).
#
# Ported from AExp-K2.  C64MEGA65's config.vhd has a different shape to AExp's:
# four welcome/help pages instead of eight, a 43x30 page geometry instead of
# 39x28 (the C64 core uses the 16x16 font), page footers written by hand rather
# than auto-appended, and no OPTM_G_OSMKEY rows to reclaim.

set K2_HELP_COLUMNS 43
set K2_HELP_ROWS    30

proc k2_help_constant {repo_dir name filename} {
   global K2_HELP_COLUMNS K2_HELP_ROWS
   set fd [open [file join $repo_dir K2 help $filename] r]
   set lines [split [string trimright [read $fd] "\n"] "\n"]
   close $fd
   if {[llength $lines] > $K2_HELP_ROWS} {
      error "K2 help: $filename exceeds $K2_HELP_ROWS content rows"
   }
   foreach line $lines {
      if {[string length $line] > $K2_HELP_COLUMNS || [regexp {[^ -~]} $line]} {
         error "K2 help: non-ASCII or over-wide line in $filename: $line"
      }
   }
   set literals {}
   foreach line $lines {
      set escaped [string map [list {"} {""}] $line]
      lappend literals "   \"$escaped\\n\""
   }
   return "constant $name : string :=\n[join $literals " &\n"];"
}

proc k2_replace_constant {text name replacement} {
   # Use indices rather than regsub substitution: VHDL contains literal \n
   # and '&', which must not be interpreted as replacement escapes.
   set pattern "constant\\s+$name\\s*:\\s*string\\s*:="
   if {![regexp -indices $pattern $text span]} {
      error "K2 config: missing string constant $name"
   }
   lassign $span first last
   set last [string first ";\n" $text $last]
   if {$last < 0} { error "K2 config: unterminated constant $name" }
   incr last
   return [string replace $text $first $last "$replacement\n"]
}

# Replace a label that must appear exactly once, so an upstream rename is a
# loud build failure rather than a silently unchanged menu.
proc k2_replace_unique {textvar old new} {
   upvar 1 $textvar text
   set first [string first $old $text]
   if {$first < 0 || [string first $old $text [expr {$first + 1}]] >= 0} {
      error "K2 config: expected exactly one occurrence of $old"
   }
   set text [string map [list $old $new] $text]
}

proc k2_config_variant {repo_dir} {
   set source_name [file join $repo_dir CORE vhdl config.vhd]
   set fd [open $source_name r]
   set config_text [read $fd]
   close $fd

   foreach {name filename} {
      SCR_WELCOME welcome.txt
      HELP_1      about.txt
      HELP_2      keyboard.txt
      HELP_3      status.txt
   } {
      set config_text [k2_replace_constant $config_text $name \
         [k2_help_constant $repo_dir $name $filename]]
   }

   set config_text [k2_replace_constant $config_text CORENAME \
      {constant CORENAME : string := "Commodore 64 for Wildbits/K2 V5.2";}]

   # Keep the K2's saved settings separate from a MEGA65 c64mega65 file that
   # may live on the same card; the two menus are not interchangeable.
   set config_text [k2_replace_constant $config_text CFG_FILE \
      {constant CFG_FILE : string := "/c64/c64k2";}]

   # Menu labels that name MEGA65-only hardware.  (The menu-navigation key is
   # named in K2/help/keyboard.txt, which already replaces HELP_2 wholesale.)
   #
   # Keep this SHORT.  OPTM_ITEMS is charged word-for-character against
   # MENU_HEAP_SIZE (1664), and upstream leaves only 17 words of headroom; the
   # full "Wildbits/K2" spelling would eat 5 of them.  The board is already
   # named in CORENAME, on every help page and on the LCD.  tb_k2_menu asserts
   # the exact budget.
   k2_replace_unique config_text {" C64 for MEGA65\n"} {" C64 for K2\n"}

   set output_dir [file join $repo_dir K2 build generated]
   file mkdir $output_dir
   set output_name [file join $output_dir config.vhd]
   set fd [open $output_name w]
   puts $fd "-- Generated by K2/scripts/config_variant.tcl; do not edit."
   puts -nonewline $fd $config_text
   close $fd
   return $output_name
}

# Update an existing project too, so users need not recreate the MIG project
# just to switch to the K2 menu. No other source files are replaced.
proc k2_use_config_variant {repo_dir} {
   set variant [k2_config_variant $repo_dir]
   set original [get_files -quiet [file join $repo_dir CORE vhdl config.vhd]]
   if {[llength $original]} {
      remove_files $original
   }
   if {![llength [get_files -quiet $variant]]} {
      add_files -norecurse $variant
   }
   set_property FILE_TYPE {VHDL 2008} [get_files $variant]
   update_compile_order -fileset sources_1
}
