#!/usr/bin/env python3
"""Emit the self-contained RLE ROM for the K2 LCD's C64 identification image.

PLACEHOLDER ARTWORK (milestone M5 replaces it).  This draws a C64 screen --
light-blue border around a blue field with a large "C64" -- using the authentic
VIC-II (Pepto) palette.  Unlike AExp's generate_lcd_logo.py it needs no SVG,
rsvg-convert or Pillow, so the ROM can always be regenerated from a bare
checkout.  The output interface matches AExp-K2 generate_lcd_logo.py's ROM.
"""
import argparse
from pathlib import Path

ASSETS = Path(__file__).resolve().parents[1] / "assets" / "lcd"
WIDTH, HEIGHT = 240, 280
MAX_RUN = 4096
ROM_WORDS = 4096

# VIC-II (Pepto) colours actually used, index 0 first.
PALETTE = [
    (0x35, 0x28, 0x79),   # 0: blue      (screen background)
    (0x6C, 0x5E, 0xB5),   # 1: light blue (border and text)
]

BORDER = 26   # pixels of border on every edge

GLYPHS = {
    "C": [".###.", "#...#", "#....", "#....", "#....", "#...#", ".###."],
    "6": ["..##.", ".#...", "#....", "####.", "#...#", "#...#", ".###."],
    "4": ["...#.", "..##.", ".#.#.", "#..#.", "#####", "...#.", "...#."],
}
TEXT = "C64"
SCALE = 12
GAP = 1       # blank glyph columns between characters


def render():
    px = [[0] * WIDTH for _ in range(HEIGHT)]
    for y in range(HEIGHT):
        for x in range(WIDTH):
            if x < BORDER or x >= WIDTH - BORDER or y < BORDER or y >= HEIGHT - BORDER:
                px[y][x] = 1

    glyph_w, glyph_h = 5, 7
    text_w = (len(TEXT) * glyph_w + (len(TEXT) - 1) * GAP) * SCALE
    x0 = (WIDTH - text_w) // 2
    y0 = (HEIGHT - glyph_h * SCALE) // 2
    for n, ch in enumerate(TEXT):
        rows = GLYPHS[ch]
        cx = x0 + n * (glyph_w + GAP) * SCALE
        for gy in range(glyph_h):
            for gx in range(glyph_w):
                if rows[gy][gx] != "#":
                    continue
                for sy in range(SCALE):
                    for sx in range(SCALE):
                        px[y0 + gy * SCALE + sy][cx + gx * SCALE + sx] = 1
    return [c for row in px for c in row]


def encode(indices):
    runs = []
    for color in indices:
        if runs and runs[-1][1] == color and runs[-1][0] < MAX_RUN:
            count, _ = runs[-1]
            runs[-1] = (count + 1, color)
        else:
            runs.append((1, color))
    return [((count - 1) << 4) | color for count, color in runs]


def decode(words):
    return [word & 15 for word in words for _ in range((word >> 4) + 1)]


def rgb565(rgb):
    r, g, b = rgb
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def generate(output_dir, test_vectors):
    indices = render()
    words = encode(indices)
    assert decode(words) == indices, "RLE round-trip failed"
    assert len(words) <= ROM_WORDS, f"{len(words)} runs exceed the {ROM_WORDS}-word ROM"

    out = [
        "// Generated by K2/scripts/generate_c64_logo.py; do not edit.",
        "// PLACEHOLDER artwork: a C64 screen in the VIC-II palette. See M5.",
        f"// {WIDTH}x{HEIGHT}, 16 RGB565 colors, {len(words)} RLE words "
        f"({len(words) * 2} bytes).",
        "module c64_logo_rom (",
        "    input wire [15:0] run_address_i,",
        "    output wire [15:0] run_word_o,",
        "    input wire [3:0] palette_address_i,",
        "    output wire [15:0] palette_color_o",
        ");",
        f'    (* rom_style = "distributed" *) logic [15:0] runs [0:{ROM_WORDS - 1}];',
        '    (* rom_style = "distributed" *) logic [15:0] palette [0:15];',
        "    initial begin",
    ]
    for i in range(16):
        rgb = PALETTE[i] if i < len(PALETTE) else PALETTE[0]
        out.append(f"        palette[{i}] = 16'h{rgb565(rgb):04x};")
    for i in range(ROM_WORDS):
        word = words[i] if i < len(words) else 0
        out.append(f"        runs[{i}] = 16'h{word:04x};")
    out += [
        "    end",
        "    assign run_word_o = runs[run_address_i[11:0]];",
        "    assign palette_color_o = palette[palette_address_i];",
        "endmodule",
        "",
    ]
    output_dir.mkdir(parents=True, exist_ok=True)
    target = output_dir / "c64_logo_rom.sv"
    target.write_text("\n".join(out))

    if test_vectors:
        colors = [rgb565(PALETTE[i] if i < len(PALETTE) else PALETTE[0])
                  for i in range(16)]
        (output_dir / "expected_pixels.mem").write_text(
            "".join(f"{colors[index]:04x}\n" for index in indices),
            encoding="ascii")

    print(f"LCD: {WIDTH}x{HEIGHT}; {len(words)} runs; "
          f"{len(words) * 2 + 32} encoded bytes; "
          f"{ROM_WORDS * 2 + 32} bytes including ROM padding; round-trip PASS")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=ASSETS)
    parser.add_argument("--test-vectors", action="store_true")
    args = parser.parse_args()
    generate(args.output_dir, args.test_vectors)
